Auto3D/Web/Auto3D.Web/Areas/Administration/Controllers/CompanyLogosController.cs
namespace Auto3D.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.Filters;
    using Auto3D.Web.ViewModels._AdministratorInputModels.CompanyLogos;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class CompanyLogosController : AdministrationController
    {
        private readonly ICompanyLogosService companyLogosServices;
        private readonly IWebHostEnvironment environment;

        public CompanyLogosController(
            ICompanyLogosService companyLogosServices,
            IWebHostEnvironment environment)
        {
            this.companyLogosServices = companyLogosServices;
            this.environment = environment;
        }

        public IActionResult Create()
        {
            var model = new CompanyLogoInputModel();
            return this.View(model);
        }

        [HttpPost]
        [ModelStateValidationActionFilter]
        public async Task<IActionResult> Create(CompanyLogoInputModel input)
        {
            string imagePath = this.GetImagePath();

            await this.companyLogosServices.CreateAsync(input, imagePath);

            return this.RedirectToAction("Index", "Home", new { area = "" });
        }

        private string GetImagePath()
        {
            return $"{this.environment.WebRootPath}/companyLogos";
        }
    }
}

Auto3D/Web/Auto3D.Web/Areas/Administration/Views/CompanyLogos/Create.cshtml
@model Auto3D.Web.ViewModels._AdministratorInputModels.CompanyLogos.CompanyLogoInputModel
@{ ViewData["Title"] = "Add company logo.";}

<section class="p-3 p-md-5 m-md-3" style="background: #EEF2FF;">
    <div class="container">
        <h3 class="text-center w-responsive mx-auto mb-5">
            @this.ViewData["Title"]
        </h3>

        <div class="row">

            <div class="col-md-6 mb-md-0 mb-0  ">

                <form id="contact-form" name="contact-form" enctype="multipart/form-data" asp-controller="CompanyLogos" asp-action="Create" method="post">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="md-form mb-0 form-group">
                                <label asp-for="Picture"></label>
                                <input asp-for="Picture" class="form-control-file" />
                                <span asp-validation-for="Picture" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="text-center text-md-left">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section> 