Auto3D/Web/Auto3D.Web/Controllers/OrdersController.cs
namespace Auto3D.Web.Controllers
{
    using System.Threading.Tasks;

    using Auto3D.Data.Models;
    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.Filters;
    using Auto3D.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : BaseController
    {
        private readonly IOrdersService ordersService;
        private readonly UserManager<ApplicationUser> userManager;

        public OrdersController(
            IOrdersService ordersService,
            UserManager<ApplicationUser> userManager)
        {
            this.ordersService = ordersService;
            this.userManager = userManager;
        }

        public IActionResult Create()
        {
            var model = new OrderCreateInputModel();
            return this.View(model);
        }

        [HttpPost]
        [ModelStateValidationActionFilter]
        public async Task<IActionResult> Create(OrderCreateInputModel createInputModel)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.ordersService.CreateAsync(createInputModel, user);
            return this.RedirectToAction("Products", "ReviewAll");
        }
    }
}

Auto3D/Web/Auto3D.Web/Controllers/ShoppingCartController.cs
namespace Auto3D.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Auto3D.Common;
    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.Common;
    using Auto3D.Web.Helpers;
    using Auto3D.Web.ViewModels.ShoppingCart;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingCartController : BaseController
    {
        private readonly IShoppingCartsService shoppingCartService;

        public ShoppingCartController(IShoppingCartsService shoppingCartService)
        {
            this.shoppingCartService = shoppingCartService;
        }

        public async Task<IActionResult> Index(ShoppingCartProductsAllViewModel shoppingCartProductsAllViewModel)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                if (shoppingCartProductsAllViewModel.Coupon != null)
                {
                    await this.shoppingCartService.AddCouponToShoppingCart(username, shoppingCartProductsAllViewModel.Coupon);
                }

                var shoppingCart = await this.shoppingCartService.GetAllShoppingCartProductsAsync(username);
                shoppingCartProductsAllViewModel.Products = shoppingCart;
                return this.View(shoppingCartProductsAllViewModel);
            }

            var cart = this.GetShoppingCartFromSession();
            shoppingCartProductsAllViewModel.Products = cart;

            return this.View(shoppingCartProductsAllViewModel);
        }

        public async Task<IActionResult> Add(int id, int quantity)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                await this.shoppingCartService.AddProductToShoppingCartAsync(id, username, 1);
            }
            else
            {
                var cart = this.GetShoppingCartFromSession();
                var shoppingCartProduct = await this.shoppingCartService.GetGuestShoppingCartProductToAdd(id, quantity);

                var cartAsList = cart.ToList();
                cartAsList.Add(shoppingCartProduct);
                this.HttpContext.Session.SetObjectAsJson(WebConstants.ShoppingCartSessionKey, cartAsList);
            }

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id, int newQuantity)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                await this.shoppingCartService.EditShoppingCartProductAsync(id, username, newQuantity);
            }
            else
            {
                var cart = this.GetShoppingCartFromSession();
                cart = this.shoppingCartService.EditGuestShoppingCartProduct(id, cart.ToArray(), newQuantity).ToArray();
                this.HttpContext.Session.SetObjectAsJson(WebConstants.ShoppingCartSessionKey, cart);
            }

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                await this.shoppingCartService.DeleteProductFromShoppingCart(id, username);
            }
            else
            {
                var cart = this.GetShoppingCartFromSession();
                cart = this.shoppingCartService.DeleteProductFromGuestShoppingCart(id, cart.ToArray()).ToArray();
                this.HttpContext.Session.SetObjectAsJson(WebConstants.ShoppingCartSessionKey, cart);
            }

            return this.RedirectToAction("Index");
        }

        private IEnumerable<ShoppingCartProductViewModel> GetShoppingCartFromSession()
        {
            return this.HttpContext.Session
                   .GetObjectFromJson<ShoppingCartProductViewModel[]>(WebConstants.ShoppingCartSessionKey) ??
                   new List<ShoppingCartProductViewModel>().ToArray();
        }
    }
}

Auto3D/Web/Auto3D.Web/Views/ShoppingCart/Index.cshtml
@model Auto3D.Web.ViewModels.ShoppingCart.ShoppingCartProductsAllViewModel
@{ ViewData["Title"] = "Shopping Cart";
    var shoppingCartUserId = Model.Products.Select(x => x.ShoppingCartUserId).FirstOrDefault();
    var shoppingCartCoupon = Model.Products.Select(x => x.ProductDiscount != "No Discount").FirstOrDefault();}


    <div class="container body-content">
        <h2 class="text-center py-3 my-3">@this.ViewData["Title"]</h2>
        <table class="table table-hover table-borderless border shadow" style="width: 100%" id="shoppingCart">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Product Name</th>
                    <th scope="col" class="text-center">Car Brand</th>
                    <th scope="col" class="text-center">Car Model</th>
                    <th scope="col" class="text-center">Car Model Year</th>
                    <th scope="col" class="text-center">Product Price</th>
                    @if (shoppingCartCoupon)
                    {
                        <th scope="col" class="text-center">Coupon Discount</th>}

                    <th scope="col" class="text-center">Quantity</th>
                    <th scope="col" class="text-center">Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Products)
                {
                <tr>
                    <td>
                        <a class="text-dark" asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@item.ProductId">
                            @item.ProductName
                        </a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CarBrand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CarModel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CarModelYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductPrice)$
                    </td>
                    @if (shoppingCartCoupon)
                    {
                @if (item.ProductDiscount != "No Discount")
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductDiscount)$
                    </td> }
                else
                {
                    <td>
                        Promotion
                    </td>}
                    }
                     <td>
                @if (this.User.IsInRole(GlobalConstants.UserRoleName))
                {
                    <form method="post" asp-area="" asp-controller="ShoppingCart" asp-action="Edit" asp-route-id="@item.Id" asp-route-newQuantity="newQuantity">
                        <div class="row">
                            <input type="number" min="1" id="newQuantity" name="newQuantity" class="form-control form-control-sm col-sm-3" value="@item.Quantity" />&nbsp;
                            <button type="submit" class="btn btn-sm btn-outline-primary">Edit</button>
                        </div>
                    </form> }
                else
                {
                <form class="text-center" method="post" asp-area="" asp-controller="ShoppingCart" asp-action="Edit" asp-route-id="@item.ProductId" asp-route-newQuantity="newQuantity">
                    <div class="row">
                        <input type="number" id="newQuantity" name="newQuantity" class="form-control form-control-sm col-md-3" value="@item.Quantity" />
                        <button type="submit" class="btn btn-sm btn-outline-primary">Edit</button>
                    </div>
                </form>}
               </td>
               <td>
                 @if (this.User.IsInRole(GlobalConstants.UserRoleName))
                 {
               @Html.ActionLink("Delete", "Delete", new { id = item.Id }) }
               else
               {
                @Html.ActionLink("Delete", "Delete", new { id = item.ProductId })}
             </td>
               </tr>
                }
            </tbody>
        </table>
        <div class="">
            <div class="text-center">
                <h5>Total sum: @Model.Products.Sum(x => x.ShoppingCartProductTotalPrice) $</h5>
                <div class="row d-flex justify-content-around mb-3">

                    @if (this.User.IsInRole(GlobalConstants.UserRoleName))
                    {
                <div class="col text-left">
                    <form method="get" asp-controller="ShoppingCart" asp-action="Index">

                        <div class="form-group">
                            <input class="btn btn-outline-primary" type="text" asp-for="Coupon" />
                            <input class="btn btn-outline-primary" type="submit" value="Discount" />
                        </div>

                    </form>
                </div>
                                <div class="col text-right">
                                    <a type="submit" class="btn btn-primary" asp-area="" asp-controller="Orders" asp-action="Create">Поръчай</a>
                                    </div>}
                                </div>
                                            </div>
        </div>
    </div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#shoppingCart')
                .addClass('nowrap')
                .dataTable({
                    responsive: true,
                });
        });
    </script>
}