Auto3D/Web/Auto3D.Web/Controllers/ProductsController.cs
namespace Auto3D.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    public class ProductsController : BaseController
    {
        private readonly IProductsService productsService;
        private readonly IWebHostEnvironment environment;

        public ProductsController(
            IProductsService productsService,
            IWebHostEnvironment environment)
        {
            this.productsService = productsService;
            this.environment = environment;
        }

        public async Task<IActionResult> All(ProductsAllViewModel productsAllViewModel, int carId)
        {
            var products = await this.productsService.GetAllProductsByCarIdAsync(carId);

            if (productsAllViewModel.SearchString != null)
            {
                products = this.productsService.GetProductsFromSearch(productsAllViewModel.SearchString, productsAllViewModel.CarId).ToList();
            }

            products = this.productsService.SortBy(products.ToArray(), productsAllViewModel.Sorter).ToList();

            var pageNumber = productsAllViewModel.PageNumber ?? 1;
            var pageSize = productsAllViewModel.PageSize ?? 6;
            var pageProductsAllViewModel = products.ToPagedList(pageNumber, pageSize);

            productsAllViewModel.Products = pageProductsAllViewModel;

            //carsAllViewModel.DistrictName = this.districtsService.GetDistrict(carsAllViewModel.DistrictId).Name;

            return this.View(productsAllViewModel);
        }

        public async Task<IActionResult> ReviewAll(ProductsAllViewModel productsAllViewModel)
        {
            var products = await this.productsService.ReviewAllProductsAsync();

            if (productsAllViewModel.SearchString != null)
            {
                products = this.productsService.GetProductsFromSearch(productsAllViewModel.SearchString, 0).ToList();
            }

            products = this.productsService.SortBy(products.ToArray(), productsAllViewModel.Sorter).ToList();

            var pageNumber = productsAllViewModel.PageNumber ?? 1;
            var pageSize = productsAllViewModel.PageSize ?? 6;
            var pageProductsAllViewModel = products.ToPagedList(pageNumber, pageSize);

            productsAllViewModel.Products = pageProductsAllViewModel;

            return this.View(productsAllViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            string imagePath = $"{this.environment.WebRootPath}/productsPictures";

            var product = await this.productsService.GetDetailsViewModelByIdAsync(id, imagePath);

            return this.View(product);
        }
    }
}

Auto3D/Web/Auto3D.Web/Controllers/ShoppingCartController.cs
namespace Auto3D.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Auto3D.Common;
    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.Common;
    using Auto3D.Web.Helpers;
    using Auto3D.Web.ViewModels.ShoppingCart;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingCartController : BaseController
    {
        private readonly IShoppingCartsService shoppingCartService;

        public ShoppingCartController(IShoppingCartsService shoppingCartService)
        {
            this.shoppingCartService = shoppingCartService;
        }

        public async Task<IActionResult> Index(ShoppingCartProductsAllViewModel shoppingCartProductsAllViewModel)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                if (shoppingCartProductsAllViewModel.Coupon != null)
                {
                    await this.shoppingCartService.AddCouponToShoppingCart(username, shoppingCartProductsAllViewModel.Coupon);
                }

                var shoppingCart = await this.shoppingCartService.GetAllShoppingCartProductsAsync(username);
                shoppingCartProductsAllViewModel.Products = shoppingCart;
                return this.View(shoppingCartProductsAllViewModel);
            }

            var cart = this.GetShoppingCartFromSession();
            shoppingCartProductsAllViewModel.Products = cart;

            return this.View(shoppingCartProductsAllViewModel);
        }

        public async Task<IActionResult> Add(int id, int quantity)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                await this.shoppingCartService.AddProductToShoppingCartAsync(id, username, 1);
            }
            else
            {
                var cart = this.GetShoppingCartFromSession();
                var shoppingCartProduct = await this.shoppingCartService.GetGuestShoppingCartProductToAdd(id, quantity);

                var cartAsList = cart.ToList();
                cartAsList.Add(shoppingCartProduct);
                this.HttpContext.Session.SetObjectAsJson(WebConstants.ShoppingCartSessionKey, cartAsList);
            }

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id, int newQuantity)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                await this.shoppingCartService.EditShoppingCartProductAsync(id, username, newQuantity);
            }
            else
            {
                var cart = this.GetShoppingCartFromSession();
                cart = this.shoppingCartService.EditGuestShoppingCartProduct(id, cart.ToArray(), newQuantity).ToArray();
                this.HttpContext.Session.SetObjectAsJson(WebConstants.ShoppingCartSessionKey, cart);
            }

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (this.User.IsInRole(GlobalConstants.UserRoleName))
            {
                var username = this.User.Identity.Name;
                await this.shoppingCartService.DeleteProductFromShoppingCart(id, username);
            }
            else
            {
                var cart = this.GetShoppingCartFromSession();
                cart = this.shoppingCartService.DeleteProductFromGuestShoppingCart(id, cart.ToArray()).ToArray();
                this.HttpContext.Session.SetObjectAsJson(WebConstants.ShoppingCartSessionKey, cart);
            }

            return this.RedirectToAction("Index");
        }

        private IEnumerable<ShoppingCartProductViewModel> GetShoppingCartFromSession()
        {
            return this.HttpContext.Session
                   .GetObjectFromJson<ShoppingCartProductViewModel[]>(WebConstants.ShoppingCartSessionKey) ??
                   new List<ShoppingCartProductViewModel>().ToArray();
        }
    }
}

Auto3D/Web/Auto3D.Web/Views/Shared/Components/ShoppingCartComponent/Default.cshtml
@model IEnumerable<Auto3D.Web.ViewModels.ShoppingCart.ShoppingCartProductViewModel>

@if (!this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
<ul class="nav navbar-nav navbar-right">
    <li class="nav-item dropdown col-md-12" style="max-width: 100%">
        <div class="dropdown collapse navbar-collapse d-flex" id="navbarNav">
            <div class="dropdown-toggle nav-link text-white" id="dropdownMenuLink" data-toggle="dropdown">
                <i class="fas fa-cart-shopping fa-2xl"></i>&nbsp;
            </div>
            @if (Model.Count() != 0)
            {
<span class="badge badge-pill badge-light">@Model.Count()</span>                }
            <div class="dropdown-menu">
                @foreach (var shopingCartProduct in Model)
                {
<div class="d-flex justify-content-around">
    <a class="dropdown-item col-md-11" asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@shopingCartProduct.ProductId">
        <img src="@shopingCartProduct.ProductPictureUrl" width="50" height="50">
        <span>@shopingCartProduct.ProductName</span>
        <span> @shopingCartProduct.Quantity x </span>
        @if (shopingCartProduct.ProductDiscount == "No Discount")
        {
            <span><b>$@shopingCartProduct.ProductPrice</b></span> }
                                else
                                {
                                    <span><b>$@shopingCartProduct.ProductPrice/@shopingCartProduct.ProductDiscount</b></span>
                                }
    </a>
    <a class="col-md-1 text-danger px-0" asp-area="" asp-controller="ShoppingCart" asp-action="Delete" asp-route-id="@shopingCartProduct.Id">
        <i class="fas fa-times"></i>
    </a>
</div>}
                @if (!Model.Any())
                {
<a class="text-center dropdown-item">
    <em class="text-muted">Empty shopping cart</em>
</a>}
                <div class="text-center">
                    <b>Total sum: $@(Model.Sum(x => x.ShoppingCartProductTotalPrice))</b>
                </div>
                <a class="dropdown-item text-center" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                    Open shopping cart
                </a>
            </div>
        </div>
    </li>
</ul>}