Auto3D/Web/Auto3D.Web/Areas/Administration/Controllers/CarBrandsController.cs
namespace Auto3D.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.Filters;
    using Auto3D.Web.ViewModels._AdministratorInputModels.CarBrands;
    using Auto3D.Web.ViewModels.CarBrands;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class CarBrandsController : AdministrationController
    {
        private readonly ICarBrandsService carBrandsService;

        public CarBrandsController(
            ICarBrandsService carBrandsService)
        {
            this.carBrandsService = carBrandsService;
        }

        public IActionResult Create()
        {
            var model = new CarBrandCreateInputModel();
            return this.View(model);
        }

        [HttpPost]
        [ModelStateValidationActionFilter]
        public async Task<IActionResult> Create(CarBrandCreateInputModel createInputModel)
        {
            var fileType = createInputModel.Logo.ContentType.Split('/')[1];
            if (!this.IsImageTypeValid(fileType))
            {
                return this.View(createInputModel);
            }

            await this.carBrandsService.CreateAsync(createInputModel);
            return this.RedirectToAction("Index", "Home", new { area = "" });
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var carBrandToDelete = await this.carBrandsService.GetDeleteViewModelByIdAsync(id);
            return this.View(carBrandToDelete);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CarBrandDeleteViewModel carBrandDeleteViewModel)
        {
            var id = carBrandDeleteViewModel.Id;
            await this.carBrandsService.DeleteByIdAsync(id);
            return this.RedirectToAction("Index", "Home", new { area = "" });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var carBrandToEdit = await this.carBrandsService.GetEditViewModelByIdAsync(id);

            return this.View(carBrandToEdit);
        }

        [HttpPost]
        [ModelStateValidationActionFilter]
        public async Task<IActionResult> Edit(CarBrandEditViewModel carBrandEditViewModel)
        {
            if (carBrandEditViewModel.Logo != null)
            {
                var fileType = carBrandEditViewModel.Logo.ContentType.Split('/')[1];
                if (!this.IsImageTypeValid(fileType))
                {
                    return this.View(carBrandEditViewModel);
                }
            }

            await this.carBrandsService.EditAsync(carBrandEditViewModel);
            return this.RedirectToAction("Index", "Home", new { area = "" });
        }
    }
}

Auto3D/Web/Auto3D.Web/Controllers/CarsController.cs
namespace Auto3D.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.ViewModels.Cars;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    public class CarsController : BaseController
    {
        private readonly ICarsService carsService;

        public CarsController(
            ICarsService carsService)
        {
            this.carsService = carsService;
        }

        public async Task<IActionResult> All(CarsAllViewModel carsAllViewModel, int brandId)
        {
            var cars = await this.carsService.GetAllCarsByBrandIdAsync(brandId);

            if (carsAllViewModel.SearchString != null)
            {
                cars = this.carsService.GetProductsFromSearch(carsAllViewModel.SearchString, carsAllViewModel.BrandId).ToList();
            }

            cars = this.carsService.SortBy(cars.ToArray(), carsAllViewModel.Sorter).ToList();

            var pageNumber = carsAllViewModel.PageNumber ?? 1;
            var pageSize = carsAllViewModel.PageSize ?? 6;
            var pagecarsAllViewModel = cars.ToPagedList(pageNumber, pageSize);

            carsAllViewModel.Cars = pagecarsAllViewModel;

            //carsAllViewModel.DistrictName = this.districtsService.GetDistrict(carsAllViewModel.DistrictId).Name;

            return this.View(carsAllViewModel);
        }
    }
}

Auto3D/Web/Auto3D.Web/Controllers/HomeController.cs
namespace Auto3D.Web.Controllers
{
    using System.Diagnostics;
    using System.Threading.Tasks;

    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.ViewModels;
    using Auto3D.Web.ViewModels.CarBrands;
    using Auto3D.Web.ViewModels.Index;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        private readonly ICarBrandsService carBrandsService;
        private readonly IProductsService productsService;
        private readonly IPartnerLogosService partnerLogosService;
        private readonly IWebHostEnvironment environment;

        public HomeController(
            ICarBrandsService carBrandsService,
            IProductsService productsService,
            IPartnerLogosService partnerLogosService,
            IWebHostEnvironment environment)
        {
            this.carBrandsService = carBrandsService;
            this.productsService = productsService;
            this.partnerLogosService = partnerLogosService;
            this.environment = environment;
        }

        public async Task<IActionResult> Index(IndexAllViewModel allIndexElementsViewModel)
        {
            var imagePath = $"{this.environment.WebRootPath}/partnerLogos";

            var allCarBrands = await this.carBrandsService.GetAllCarBrandsAsync();
            var reviewProducts = await this.productsService.ReviewLastAddedProductsAsync();
            var partnerLogos = await this.partnerLogosService.GetAllLogosAsync(imagePath);

            allIndexElementsViewModel.Brands = allCarBrands;
            allIndexElementsViewModel.Products = reviewProducts;
            allIndexElementsViewModel.Logos = partnerLogos;

            return this.View(allIndexElementsViewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Auto3D/Web/Auto3D.Web/Controllers/InquiriesController.cs
namespace Auto3D.Web.Controllers
{
    using System.Threading.Tasks;

    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.Filters;
    using Auto3D.Web.ViewModels.Inquiries;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class InquiriesController : BaseController
    {
        private readonly IInquiriesService inquiriesService;
        private readonly IWebHostEnvironment environment;

        public InquiriesController(
            IInquiriesService inquiriesService,
            IWebHostEnvironment environment)
        {
            this.inquiriesService = inquiriesService;
            this.environment = environment;
        }

        public IActionResult Create()
        {
            var model = new InquiryCreateInputModel();
            return this.View(model);
        }

        [HttpPost]
        [ModelStateValidationActionFilter]
        public async Task<IActionResult> Create(InquiryCreateInputModel input)
        {
            var imagePath = $"{this.environment.WebRootPath}/inquiriesPictures";

            await this.inquiriesService.CreateAsync(input, imagePath);

            return this.RedirectToAction("Products", "ReviewAll");
        }
    }
}

Auto3D/Web/Auto3D.Web/Controllers/ProductsController.cs
namespace Auto3D.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Auto3D.Services.Data.Contracts;
    using Auto3D.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    public class ProductsController : BaseController
    {
        private readonly IProductsService productsService;
        private readonly IWebHostEnvironment environment;

        public ProductsController(
            IProductsService productsService,
            IWebHostEnvironment environment)
        {
            this.productsService = productsService;
            this.environment = environment;
        }

        public async Task<IActionResult> All(ProductsAllViewModel productsAllViewModel, int carId)
        {
            var products = await this.productsService.GetAllProductsByCarIdAsync(carId);

            if (productsAllViewModel.SearchString != null)
            {
                products = this.productsService.GetProductsFromSearch(productsAllViewModel.SearchString, productsAllViewModel.CarId).ToList();
            }

            products = this.productsService.SortBy(products.ToArray(), productsAllViewModel.Sorter).ToList();

            var pageNumber = productsAllViewModel.PageNumber ?? 1;
            var pageSize = productsAllViewModel.PageSize ?? 6;
            var pageProductsAllViewModel = products.ToPagedList(pageNumber, pageSize);

            productsAllViewModel.Products = pageProductsAllViewModel;

            //carsAllViewModel.DistrictName = this.districtsService.GetDistrict(carsAllViewModel.DistrictId).Name;

            return this.View(productsAllViewModel);
        }

        public async Task<IActionResult> ReviewAll(ProductsAllViewModel productsAllViewModel)
        {
            var products = await this.productsService.ReviewAllProductsAsync();

            if (productsAllViewModel.SearchString != null)
            {
                products = this.productsService.GetProductsFromSearch(productsAllViewModel.SearchString, 0).ToList();
            }

            products = this.productsService.SortBy(products.ToArray(), productsAllViewModel.Sorter).ToList();

            var pageNumber = productsAllViewModel.PageNumber ?? 1;
            var pageSize = productsAllViewModel.PageSize ?? 6;
            var pageProductsAllViewModel = products.ToPagedList(pageNumber, pageSize);

            productsAllViewModel.Products = pageProductsAllViewModel;

            return this.View(productsAllViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            string imagePath = $"{this.environment.WebRootPath}/productsPictures";

            var product = await this.productsService.GetDetailsViewModelByIdAsync(id, imagePath);

            return this.View(product);
        }
    }
}

Auto3D/Web/Auto3D.Web/Views/Home/Index.cshtml
@{ this.ViewData["Title"] = "Home Page"; }

@section Styles{
    <link href="@Url.Content("~/css/sideNav.css")" rel="stylesheet" type="text/css" />
}


<div class="position-relative overflow-hidden pt-3 p-md-3 mb-2 text-center bg-light" id="zero" style="background: white !important; ">
    <div class="col-md-12 mx-auto mt-2 text-dark ">
        <h3>Наслади се на @GlobalConstants.SystemName и открий най-добрите оферти за теб!  <button class="btn btn-primary">Learn more</button></h3>
    </div>

    <div class="col-md-12 p-lg-0 mx-auto text-white">
        <cache expires-after="@TimeSpan.FromHours(3)">
            <partial name="_CarouselPartial" />
        </cache>
    </div>
</div>

<hr class="mb-2" />
<partial name="_CarBrandsPartial" />

<hr class="mt-2" />
<partial name="_TopPartsPartial" />

<hr />
<partial name="_PartnerLogosPartial" />

<hr />
<partial name="_ContactFormPartial" />

<partial name="_SideNavPartial" />

@section NavIndex{
    <nav class="navbar navbar-expand-lg navbar-dark py-0 text-left" style="background: #303841;">
        <div class="container-xl">
            <div class="navbar-collapse collapse" id="navbarsExample07XL">
                <ul class="navbar-nav mr-auto" >
                    <li class="nav-item">
                        <small class="border-right d"><a class="nav-link pr-2 pl-0 py-0 text-primary d-inline" href="#zero" id="first">Начало</a></small>
                    </li>
                    <li class="nav-item">
                        <small class="border-right d"><a class="nav-link pr-2 py-0 text-primary d-inline" href="#one" id="second">Марки</a></small>
                    </li>
                    <li class="nav-item">
                        <small class="border-right d"><a class="nav-link pr-2 py-0 text-primary d-inline" href="#two" id="third">Актуални</a></small>
                    </li>
                    <li class="nav-item">
                        <small class="border-right d"><a class="nav-link pr-2 py-0 text-primary d-inline" href="#three" id="fourth">Партньори</a></small>
                    </li>
                    <li class="nav-item">
                        <small><a class="nav-link pr-2 py-0 text-primary d-inline" href="#four" id="fifth">Контакти</a></small>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
}

Auto3D/Web/Auto3D.Web/Views/Home/_CarBrandsPartial.cshtml
@model Auto3D.Web.ViewModels.Index.IndexAllViewModel

@{ this.ViewData["Title"] = "Choose your car brand";}

<div class="p-3 p-md-5 m-md-3"  style="background: #888888; " id="one">
    <div class="container ">

        <h2 class="text-center text-white mb-4">
            @this.ViewData["Title"]
            @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
        <a type="button" class=" btn btn-primary" asp-area="Administration" asp-controller="CarBrands" asp-action="Create">Add Brand</a>}  
        </h2>

        <div class="row">
            @foreach (var item in Model.Brands)
            {
                <div class="col-md-3 my-4  text-center"> 
                    <a type="button" class="btn w-100 brandButtons shadow" style="height: 60px; background: #EFEFEF;" asp-area="" asp-controller="Cars" asp-action="All" asp-route-brandId="@item.Id"><img src="@item.Logo" style="width:48px;" />@item.Brand</a>
                </div>}

            @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                  <hr class="bg-white">

                  @foreach (var item in Model.Brands)
                  {
                    <div class="col-md-3 my-4  text-center">
                        <a class=" btn btn-danger w-100 brandButtons" style="height:60px" asp-area="Administration" asp-controller="CarBrands" asp-action="Edit" asp-route-id="@item.Id"><img src="@item.Logo" style="width:48px;" />@item.Brand @*<i class="fa-solid fa-trash-can text-white"></i>*@ <i class="fa-solid fa-pen-to-square"></i></a>
                    </div>}     }
        </div>
    </div>
</div>

Auto3D/Web/Auto3D.Web/Views/Home/_CarouselPartial.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img style="max-height: 550px; width:100%;" class="d-block mx-auto" src="/images/carousel/pexels-sarmad-mughal-305070.jpg" alt="First slide">
            <div class="carousel-caption d-md-block border-white">
                <h3>We are creative!</h3>
                <p>We offer the best 3d printing car parts!</p>
            </div>
        </div>
        <div class="carousel-item">
            <img style="max-height: 550px; width:100%;" class="d-block mx-auto" src="/images/carousel/pexels-vraj-shah-638479.jpg" alt="Second slide">
            <div class="carousel-caption d-md-block border-white">
                <h3>We are professionals!</h3>
                <p>We offers parts for over 10 car brands.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img style="max-height: 550px; width:100%;" class="d-block mx-auto" src="/images/carousel/pexels-maria-geller-2127037.jpg" alt="Third slide">
            <div class="carousel-caption d-md-block border-white">
                <h3>We are engineers!</h3>
                <p>Our parts are very reliable!</p>
            </div>
        </div>
 
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

@*<style>
    .carousel-control-prev-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23f00' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E");
    }

    .carousel-control-next-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23f00' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
    }
</style>*@

Auto3D/Web/Auto3D.Web/Views/Home/_ContactFormPartial.cshtml
@*@model Auto3D.Web.ViewModels.Index.IndexConfigureViewModel*@
@{ ViewData["Title"] = "Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within a matter of hours to help you.";}

    <div class="container containerContacts pt-5 pb-5" id="four">
        <!--Section heading-->
        <h2 class="text-center">Contact us</h2>
        <!--Section description-->
        <p class="text-center w-responsive mx-auto mb-5">
            @this.ViewData["Title"]
        </p>

        <div class="row">

            @*Grid column*@
            <div class="col-md-6 mb-md-0 mb-0  text-center">

                <p>
                    <a asp-controller="Inquiries" asp-action="Create">
                        <img style="height: 180px; width: 70%" class="card-img-top rounded-pill shadow" src="/images/contactForm/pexels-anna-shvets-5324968.jpg" alt="Card image cap">
                    </a>
                </p>
                <p>

                    <a type="button" style="width: 50%" class="btn btn-sm btn-outline-primary" asp-area="" asp-controller="Inquiries" asp-action="Create">Message</a>
                </p>
                @*<form id="contact-form" name="contact-form" enctype="multipart/form-data" asp-controller="DistrictViewObjects" asp-action="Create" method="post">

        <div asp-validation-summary="All" class="text-danger"></div>*@

                <!--Grid row-->
                <!--<div class="row">

        Grid column
        <div class="col-md-4">
            <div class="md-form mb-0 form-group">
                <label asp-for="Inquiry.RecipientName" class="control-label"></label>
                <input asp-for="Inquiry.RecipientName" class="form-control" />
                <span asp-validation-for="Inquiry.RecipientName" class="text-danger"></span>
            </div>
        </div>
        Grid column
        Grid column
        <div class="col-md-4">
            <div class="md-form mb-0 form-group">
                <label asp-for="Inquiry.RecipientEmail" class="control-label"></label>
                <input asp-for="Inquiry.RecipientEmail" class="form-control" />
                <span asp-validation-for="Inquiry.RecipientEmail" class="text-danger"></span>
            </div>
        </div>
        Grid column
        Grid column
        <div class="col-md-4">
            <div class="md-form mb-0 form-group">
                <label asp-for="Inquiry.RecipientPhoneNumber" class="control-label"></label>
                <input asp-for="Inquiry.RecipientPhoneNumber" class="form-control" />
                <span asp-validation-for="Inquiry.RecipientPhoneNumber" class="text-danger"></span>
            </div>
        </div>
        Grid column

    </div>
    Grid row
    Grid row
    <div class="row">
        <div class="col-md-8">
            <div class="md-form mb-0 form-group">
                <label asp-for="Inquiry.Subject" class="control-label"></label>
                <input asp-for="Inquiry.Subject" class="form-control" />
                <span asp-validation-for="Inquiry.Subject" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="md-form mb-0 form-group">
                <label asp-for="Inquiry.Pictures"></label>
                <input asp-for="Inquiry.Pictures" class="form-control-file" />
                <span asp-validation-for="Inquiry.Pictures" class="text-danger"></span>
            </div>
        </div>

    </div>
    Grid row
    Grid row
    <div class="row">

        Grid column
        <div class="col-md-12">

            <div class="md-form mb-0 form-group">
                <label asp-for="Inquiry.Message" class="control-label"></label>
                <textarea asp-for="Inquiry.Message" rows="4" class="form-control"></textarea>
                <span asp-validation-for="Inquiry.Message" class="text-danger"></span>
            </div>

        </div>
    </div>-->
                <!--Grid row-->
                @*<div class="text-center text-md-left">
                <button type="submit" class="btn btn-primary">Finish Order</button>
            </div>
        </form>

        <div class="status"></div>*@
            </div>
            <!--Grid column-->
            <!--Grid column-->
            <div class="col-md-6 text-center">
                <ul class="list-unstyled mb-0">
                    <li>
                        <i class="fas fa-map-marker-alt fa-2x"></i>
                        <p>San Francisco, CA 94126, USA</p>
                    </li>

                    <li>
                        <i class="fas fa-phone mt-4 fa-2x"></i>
                        <p>+ 01 234 567 89</p>
                    </li>

                    <li>
                        <i class="fas fa-envelope mt-4 fa-2x"></i>
                        <p>contact@mdbootstrap.com</p>
                    </li>
                </ul>
            </div>
            <!--Grid column-->

        </div>
    </div>

Auto3D/Web/Auto3D.Web/Views/Home/_PartnerLogosPartial.cshtml
@model Auto3D.Web.ViewModels.Index.IndexAllViewModel

@{ this.ViewData["Title"] = "Our partners";}

    <div class="container h-100 containerSlider pt-5 pb-5" id="three">
        <div class="row align-items-center h-100">
            <div class="container rounded containerSlider">
                <h2 class="text-center">
                    @this.ViewData["Title"]
                    @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                    {
                        <a type="button" class=" btn btn-primary" asp-area="Administration" asp-controller="PartnerLogos" asp-action="Create">Add Logo</a>}
                </h2>
                <div class="slider">
                        @if (Model.Logos.Any())
                        {
                    <div class="logos">
                            @foreach (var item in Model.Logos)
                            {

                                <img src="@item.Path" style="width:64px; height:100%" class="fab"/>
                            }
                    </div>
                    <div class="logos">
                
                            @foreach (var item in Model.Logos)
                            {

                                <img src="@item.Path" style="width: 64px; height: 100%"  class="fab"/>
                            }
                        
                        </div>
                        }
                        @*<div class="logos">

                <i class="fab fa-js fa-4x"></i>
                <i class="fab fa-linkedin-in fa-4x"></i>
                <i class="fab fa-dribbble fa-4x"></i>
                <i class="fab fa-medium-m fa-4x"></i>
                <i class="fab fa-github fa-4x"></i>
            </div>
            <div class="logos">
                <i class="fab fa-js fa-4x"></i>
                <i class="fab fa-linkedin-in fa-4x"></i>
                <i class="fab fa-dribbble fa-4x"></i>
                <i class="fab fa-medium-m fa-4x"></i>
                <i class="fab fa-github fa-4x"></i>
            </div>*@
                    </div>
                </div>
        </div>

    </div>

Auto3D/Web/Auto3D.Web/Views/Home/_SideNavPartial.cshtml
<div id="mySidenav" class="sidenav">
    <div class="side">
        <div class="my-2">
            <i class="fas fa-bars text-primary"></i>
            <a href="#zero" class="text-dark my-2" id="first">
                Начало
            </a>
        </div>
        <div class="my-2">
            <a href="#one" class="text-dark" id="second">
                Марки
            </a>
        </div>
        <div class="my-2">
            <a href="#two" class="text-dark" id="third">
                Актуални
            </a>
        </div>
        <div class="my-2">
            <a href="#three" class="text-dark " id="fifth">
                Партньори
            </a>
        </div>
        <div class="my-2">
            <a href="#four" class="text-dark " id="fourth">
                Контакти
            </a>
        </div>
    </div>
</div>

Auto3D/Web/Auto3D.Web/Views/Home/_TopPartsPartial.cshtml
@model Auto3D.Web.ViewModels.Index.IndexAllViewModel

@{ this.ViewData["Title"] = "Best Parts"; }

@section Styles{
    <link href="@Url.Content("~/css/carouselTopParts.css")" rel="stylesheet" type="text/css" />
}


<div class="album text-center pt-5 pb-5" id="two">
    <div>
        <h2> @this.ViewData["Title"]</h2>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 ">
            @foreach (var item in Model.Products)
            {
        <div class="col-lg-4 col-sm-12 col-12 d-flex flex-column my-2">
            <div class="card">

                <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">
                    <img style="height: 250px; width: 100%" class="card-img-top shadow" src="@item.PictureUrl" alt="Card image cap">
                </a>

                <div class="card-body p-0">
                    <h5 class="card-text m-1">@item.Name @item.CarBrand @item.CarModel @item.CarYear</h5>
   
                    @if (item.Discount == 0)
                    {
        <h4 class="card-text p-1">$@item.Price</h4> }
    else
    {
        <h4 class="card-text p-1"><small><s>$@item.Price</s></small> /$@item.Discount</h4>}

                </div>

                <div class="btn-group">
                    <a type="button" class="btn btn-sm btn-outline-secondary button" asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </div>
            </div>
        </div>}
        </div>
    </div>
</div>